.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH BOATS 1 "APRIL 2009"
.SH NAME
boats \- a race scenario drawing tool
.SH SYNOPSIS
.B boats [-debug n]
.I file
.B ...
.SH DESCRIPTION
.B boats
Boat Scenario is a drawing tool. It is your ideal
companion for training sessions, rule learning, strategy
explanations and more.
All files provided in the command line will be opened
on different tabs.
.SH OPTIONS
.IP -debug
Provide debugging output
.SH AUTHOR
Thibaut GRIDEL <tgridel at free dot fr>
